/**
 * Environment Configuration - Production
 *
 * RUNTIME CONFIGURATION TAKES PRECEDENCE:
 * In production deployments, configuration is loaded from /config.json at application startup.
 * The config.json file is generated by the CDK frontend stack and contains:
 * - appApiUrl: Same-origin path ('/api') routed to the app-api ALB via CloudFront
 * - version: Application version from VERSION
 * - cognitoDomainUrl: Cognito Hosted UI domain (admin auth-providers form)
 *
 * These values below serve as FALLBACK ONLY if config.json cannot be loaded.
 * In normal production operation, these values are NOT used.
 *
 * DO NOT modify these values for deployment configuration.
 * Configuration is managed by CDK infrastructure stack.
 */
export const environment = {
    production: true,
    // Runtime values loaded from /config.json
    // These are placeholders for fallback only
    appApiUrl: '',
    version: '',
    cognitoDomainUrl: '',
};
